POST http://localhost:8000/user/create

Content-Type: application/json

{
    "name": "denilson",
    "email": "denilson@yopmail.com",
    "password": "test"
}

POST http://localhost:8000/auth/login

Content-Type: application/json

{
    "username": "denilson",
    "password": "test"
}

POST http://localhost:8000/auth/logout

Content-Type: application/json

{
    "username": "denilson",
    "password": "test"
}
